version: '3.8'

services:
  backend:
    build: backend/
    command: python /backend/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/backend
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
  frontend:
    build: frontend/
    command: npm start
    volumes:
      - /frontend/node_modules
      - ./frontend:/frontend
    ports:
      - 3000:3000

volumes:
  postgres_data:
