version: '3.8'

services:
  web:
    build: backend/.
    command: python /backend/manage.py runserver 0.0.0.0:8000
    volumes:
      - backend:/backend
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:12
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"